### ISSUE TITLE
redis sortedSet 

### ISSUE THREAD

**Issue by ExpressGit** [dongnan/LinkCache#1]
非常感谢你的linkcache插件。为我的项目提效很多。
在项目的实际开发中，我们对插件进行了扩展，加入了sotedset `有序集合，
交流：xull01@mysoft.com.cn
再次感谢！

**Comment by dongnan** [comment]
很高兴我的项目能给你带来帮助，你提到的扩展让我发现了Cache::__call的一个bug。其实Cache对象是可以直接调用Cache对象中没有但是驱动对象或驱动handler对象中定义的方法，比如你提到的有序集合如果使用的是redis就可以直接使用。
